### ISSUE TITLE
Release 0.1.0 ?

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/ndx-fiber-photometry#13]
Opening issue to not forget releasing a "stable" first version (I think we are getting there), looks like the README.md has to be updated though.

**Comment by pauladkisson** [comment]
After #22, #23, #25, #27 get merged we should be ready for release.

**Comment by weiglszonja** [comment]
> After #22, #23, #25, #27 get merged we should be ready for release.

They look great, thank you!
