### ISSUE TITLE
`FiberPhotometryResponseSeries` incorrect shape error for 1D data

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/ndx-fiber-photometry#15]
I just run `nwbinspector` on the converted sessions, and noticed that I got an incorrect shape error for `FiberPhotometryResponseSeries`:

```python-traceback
FiberPhotometryResponseSeries/data (processing/ophys/FiberPhotometryResponseSeriesGreen/data): incorrect shape - expected '[None, None]', got '(103014,)'
```

In the spec file we have restricted that the data shape should always be 2D:
https://github.com/catalystneuro/ndx-fiber-photometry/blob/2e80a7ac040ddca2873cce03aceaabd7c816a5f6/src/spec/create_extension_spec.py#L364

Shouldn't we allow it to be 1D as well? What do you think @pauladkisson @luiztauffer @alessandratrapani ? If this was intentional then we at least have to modify the description, because currently it says 1D is allowed.

**Comment by pauladkisson** [comment]
I ran into this as well, thanks for the fix @weiglszonja!

Looks like CommandedVoltageSeries has a similar issue tho:
```bash
FiberPhotometryTable/commanded_voltage_series (acquisition/fiber_photometry_table/commanded_voltage_series): incorrect shape - expected '[None, None]', got '(4,)'
```
