### ISSUE TITLE
Fiber Photometry extension description

### ISSUE THREAD

**Issue by alessandratrapani** [catalystneuro/ndx-fiber-photometry#2]
This extension aims to improve the already existing [ndx-photometry](https://github.com/catalystneuro/ndx-photometry) and eventually converge in a unique extension for fiber photometry data.

In this new version, the `FiberPhotometryTable` stores the unique combination of location, coordinates, fluorophore,`Fiber` (`Device`), `LightSource`(`Device`), `Photodetector`(`Device`), `DichroicMirror` (`Device`).
The `FiberPhotometryResponseSeries` is a 2D array where the first dimension is time and the second is the number of fibers. `FiberPhotometryResponseSeries` has an additional field: `fiber_photometry_table`, a  DynamicTableRegion that references the `FiberPhotometryTable` rows in the same order as the second dimension of `data`.

This proposed version would tackle the problem of having hundreds of 1D `FiberPhotometryResponseSeries` in the case of [multi-fiber systems](https://www.biorxiv.org/content/10.1101/2023.11.17.567425v1) where only the coordinates of the fiber implant change. 
`Fiber`, `LightSource`, `Photodetector`, `DichroicMirror`, and `OpticalFilter` are defined as devices (in a single session, there are more likely 1 to 3 different configurations of the same device, e.g., two different excitation wavelength).

Open questions:
How can we represent Modulated raw traces? With this extension, only demodulated traces are represented (each trace is the result of a single excitation source, a single fluorophore, etc.). However, we have cases where a single raw trace is amplitude or frequency modulated to encode two or more traces. Thus, we need to be able to associate more than one excitation source or more than one fluorophore to the same trace.

**Comment by rly** [comment]
Hi @alessandratrapani et al, I would like to collaborate on this with you all. I am working with the Berke Lab at UCSF also to store their photometry data in NWB by improving the already existing ndx-photometry extension. As a first step, we are converting the data from this paper https://www.cell.com/neuron/fulltext/S0896-6273(23)00550-0?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0896627323005500%3Fshowall%3Dtrue to NWB. 

I'm at the stage of collecting all the fields that they want to store and schematizing them. Could we chat sometime after the Developer Hackathon? I will take a closer look at what you have here then.
