### ISSUE TITLE
`FiberPhotometryResponseSeries` unit should be "n.a."

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/ndx-fiber-photometry#20]
This should be corrected in the example as well:
https://github.com/catalystneuro/ndx-fiber-photometry/blob/94d80c2996cf3c71bd7e6f2b2c83f9b3fb9906ff/src/pynwb/tests/integration/test_fiber_photometry.py#L203

Maybe we could "hardcode" it into the schema as well so the default is always "n.a." to avoid mistakes? @alessandratrapani

**Comment by alessandratrapani** [comment]
> Maybe we could "hardcode" it into the schema as well so the default is always "n.a." to avoid mistakes? @alessandratrapani
Agree
