### ISSUE TITLE
Optical Filter should specify 2-wavelength passband

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/ndx-fiber-photometry#6]
The optical filters from doric lenses don't really have a peak wavelength, but rather a flat pass band. See figure 3.1 [here](https://doriclenses.com/downloads/UserManual/UserManual_ilFMC_GEN3_V1.0.0.pdf).

So, instead of peak_wavelength and bandwidth, we should specify a 2-wavelength passband ex.  
```python
emission_filter = OpticalFilter(
            name="emission_filter",
            description="...",
            manufacturer="Doric Lenses",
            model="4 ports Fluorescence Mini Cube - GCaMP",
            pass_band_in_nm=(460.0, 490.0)
            filter_type="bandpass",
        )
```

**Comment by pauladkisson** [comment]
Update: In the previous comment, I missed that `bandwidth_in_nm` is already a 2-element float that would refer to the pass band in this case. But I still think at the very least the naming is a bit confusing, since bandwidth usually refers to a single width (ex. 30nm) rather than the range of the pass band (ex. 460nm-490nm).

**Comment by alessandratrapani** [comment]
I agree pass_band_in_nm is a better name for that. However I don't think we should remove the peak_wavelength, usually filters are reported as wavelength/bandwidth, eg. 920/30 nm where the 30 nm large bandwidth is centered at 920.  Maybe we can change the name in central_wavelength or something like this, but still keep this information
